# Generated by Django 2.2.4 on 2022-04-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loginapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_py', models.ForeignKey(on_delete='cascade', related_name='books_uploaded', to='loginapp.User')),
                ('users_who_likes', models.ManyToManyField(related_name='liked_books', to='loginapp.User')),
            ],
        ),
    ]
